#include <ctime>
#include <stdlib.h>

int getRandomInt()
{
	// 'std::srand' is used to seed the random number generator.
	// And what is a random number generator?
	// A random number generator is a process that generates a sequence of numbers that is unpredictable.
	// And what is a seed?
	// A seed is a number that is used to initialize the random number generator.
	// And why is it important to seed the random number generator?
	// Because the random number generator is a deterministic process.
	// And what is a deterministic process?
	// A deterministic process is a process that produces the same output given the same input.
	// And example of seed and random number generator.
	// For example, if you use the same seed to seed the random number generator, you will get the same sequence of numbers.
	// Like 'std::srand(0);' will produce the same sequence of numbers.
	// How so?
	// Because the random number generator is a deterministic process.
	std::srand(time(NULL));

	// 'rand' is used to generate a random number.
	// And what is a random number?
	// A random number is a number that is generated by a process that is unpredictable.
	return rand();
}

int getRandomInt(int max, int min = 0)
{
	return min + (rand() % max) + min;
}
